cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: 관리자(대표님)
      password: $2b$12$6z2rTtwhF.xZJC4PQ7sVvumnnGCepLynCmfGlvZx4svog9LSH7rWS
      role: admin
    client:
      email: mycommerce@example.com
      name: 고객사
      password: $2b$12$yKFOWVr.iWz0vLPH58qmzOBQVxhmwaWbVX1Itng5tdjgLRIe7QR.W
      role: client
preauthorized:
  emails: []
